### ISSUE TITLE
Licensing Issues

### ISSUE THREAD

**Issue by 108ium** [cubettech/myyna#1]
Nice project, but your license is confusing. Your readme says MIT but your license file says some proprietary EULA.

Ambiguous licensing makes it difficult to use open source projects.

Can you please simplify the license file to say MIT Lic, just like your readme file.

**Comment by kantaharikrishna** [comment]
Yes, it would be great if license issue is clarified. It would be very easy if readme file and license file say same things. Looking forward for MIT license.

**Comment by cubettech** [comment]
Updated MIT license all over project, Please download new updates
